version: 2

project_name: ark

before:
  hooks:
    - go test ./...

builds:
  - id: ark
    main: ./cmd/ark
    binary: ark
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X ark/internal.ArkVersion={{ .Version }} -X ark/internal.ArkBuild={{ .Env.ARK_BUILD_NUMBER }}

archives:
  - id: default
    ids:
      - ark
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: github

release:
  draft: false
  prerelease: auto
